#!/usr/bin/env python3
"""Optimise the distance to the Grassmannian

Try `dGr --help` for the usage.

History
    Aug 2018 - Start
    Mar 2019 - Add to git

Yuri
"""
import sys
import logging

import dGr_parser
from dGr_main import dGr_main

try:
    cmd_line_args = dGr_parser.parse_cmd_line()
except dGr_parser.ParseError as e:
    sys.exit(str(e))

logfile = cmd_line_args.basename + '.min_dist' + cmd_line_args.state + '.log'
log_format = ('%(levelname)s: %(funcName)s - %(filename)s:'
              + '\n%(message)s\n')
logging.basicConfig(filename=logfile,
                    format=log_format,
                    filemode='w',
                    level=cmd_line_args.loglevel)
logger = logging.getLogger(__name__)

dGr_main(cmd_line_args)

exit()
