cpdef int triangular(int n)
cpdef int get_n_from_triang(int i, int j)
cpdef (int, int) get_ij_from_triang(int n)
cpdef int get_n_from_triang_with_diag(int i, int j)
cpdef (int, int) get_ij_from_triang_with_diag(int n)
cpdef int get_pos_from_rectangular(int i, int a, int n)
cpdef (int, int) get_ia_from_rectangular(int pos, int n)
